//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TatarTelegram.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Chat_Chatter
    {
        public int Id { get; set; }
        public Nullable<int> Chatter { get; set; }
        public Nullable<int> Chat { get; set; }
    
        public virtual Chat Chat1 { get; set; }
        public virtual Chatter Chatter1 { get; set; }
    }
}
